version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_satisfaction_api
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    
  db:
    image: postgres:13
    container_name: customer_satisfaction_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: